### ISSUE TITLE
Sora SC Voices not working after update on Steam

### ISSUE THREAD

**Issue by MonaCage** [ZhenjianYang/SoraVoiceScripts#32]
Just wanted to let you know that after the update in the last days the voices do not work on the newest version (of SC at least).

I found a workaround in the meantime, for those interested:
Go to properties of the game in the Steam library, on the Beta tab choose the March version. After downloading it, the Voices work again.

**Comment by ZhenjianYang** [comment]
Thank you, Mona.
I'll try to fix it on this weekend.

**Comment by ZhenjianYang** [comment]
Hi,
I finished the fix.
Please download the new release [here](https://github.com/ZhenjianYang/SoraVoice/releases/latest).

**Comment by MonaCage** [comment]
Thanks for fixing it so fast.
Unfortunatly it seems there was another update today which hinders the voices from working again (at least for SC, not for FC. Don't know about TC).

**Comment by ZhenjianYang** [comment]
Hi,
Please try to get the latest release [here](https://github.com/ZhenjianYang/SoraVoice/releases/latest).

**Comment by ZeroVG** [comment]
I downloaded the latest release and replaced the old SoraVoice folder with the new one. But, it still doesnt work, what else should I do?(the problem is due to the update which I understand has already been fixed, but I seem to have trouble implementing the fix).

**Comment by ZhenjianYang** [comment]
> I downloaded the latest release and replaced the old SoraVoice folder with the new one. But, it still doesnt work, what else should I do?(the problem is due to the update which I understand has already been fixed, but I seem to have trouble implementing the fix).

Hi, try to replace 'dinput8.dll' with the new one.
Make sure you have the latest game patch installed.
And I recommend you open a new issue if you still have problems.
