### ISSUE TITLE
Text change

### ISSUE THREAD

**Issue by Caagr98** [ZhenjianYang/SoraVoiceScripts#34]
In SC [E0310_1#345](https://github.com/ZhenjianYang/SoraVoiceScripts/blob/f962033017705c389cbf2101865dfea708200668/en.sc/out.py/E0310_1.txt#L3220), the vanilla text (in Steam version at least) says "six feet under", but this mod changes it to "six arge under". Is that intentional?

**Comment by ZhenjianYang** [comment]
Hi,
We didn't change the text.
People in Zemuria use a different [Metric system](https://kiseki.fandom.com/wiki/Metric_system).

**Comment by Caagr98** [comment]
Seems I somehow got it confused with [E0311_1#4](https://github.com/ZhenjianYang/SoraVoiceScripts/blob/f962033017705c389cbf2101865dfea708200668/en.sc/out.py/E0311_1.txt#L60), which does indeed say "feet". My bad, and sorry for the accusation.
