### ISSUE TITLE
SC Only Estelle Speaks

### ISSUE THREAD

**Issue by mrwizerd** [ZhenjianYang/SoraVoiceScripts#35]
I am not sure what I have done wrong, I have 2gb roughly of voice files and I have the script files from here and Estelle speaks but no one else does.  I have the Steam version and I am running the 12-2019 version of the software so the patch will work. But no matter what I do only Estelle will speak. Is this normal or is it something wrong with my install?

**Comment by ZhenjianYang** [comment]
Hi,
Likely you missed some voice files.
There should be more than 44.8K voice files in total for SC

**Comment by mrwizerd** [comment]
Thanks for the quick response.  I am reading 44.8k voice files in the ogg folder totaling 1.5gb on disk.  I will re-rip and re-encode the files again for good measure. Is there any other thing it could be?

**Comment by mrwizerd** [comment]
Ok, I did a full install on another computer fresh.  It is working 100% properly.  SO I am doing a full reinstall on the other machine to see if it fixes it.  I figured since the two computers had the same files on them they would work the same but for some reason something is messed up.   Thanks again for your assistance time and effort.
